"use client"
import { Inter } from "next/font/google";
import React from "react";

import "./globals.css";
import { useRef, useState } from "react";
import { useContext } from 'react'

import Image from 'next/image'
import profilePic from './img/1/img2_prev_ui.png';
import I1 from './img/county/02.png';
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

import localFont from "next/font/local";
const myFont = localFont({
  src: "./font/Exo2-VariableFont_wght.ttf" ,
  display: "swap",
});

// export const metadata = {
  //   title: "Create Next App",
  //   description: "Generated by create next app",
  // };
  
  const myContext=React.createContext()

export default function RootLayout({ children }) {
  const x1=useRef()

  function navH(){
    x1.current.style.left='0%'
  }
  function closeNav(){
    x1.current.style.left='-300%'
  }

  return (
    <html lang='en' className={myFont.className}>
      <head>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"/>
      </head>
      <body className={inter.className}>
      <section className="w-[100%] text-white h-[100vh] relative img1 bg-fixed grid">
       <section className="w-[100%] h-[100%] blur-md absolute"></section>
       <section className="w-[100%] h-[100%] absolute">
         <article className="w-[100%] h-[8.5vh] relative">
          <div className="w-[100%] h-[100%] absolute g1"></div>
          <div className="w-[100%] h-[100%] absolute flex border-b-[.05px] border-[rgba(147,146,146,0.34)]">
            <NavH navH={navH}/>
            <Logo/>
            <Search/>
            <Profile/>
            <div className="w-[1.65%] h-[100%] hidden xl:flex border-r-[.05px] border-[rgba(147,146,146,0.34)]"></div>
          </div>
        </article>
      
        <article className="w-[100%] h-[8.5vh] relative hidden lg:flex">
        <div className="w-[100%] h-[100%] absolute g2"></div>
        <div className="w-[100%] h-[100%] absolute flex border-b-[.05px] border-[rgba(147,146,146,0.34)]">
          <Nav/> 
        </div>
        </article>

        <article ref={x1} className="w-[100vw] h-[100vh] lg:hidden left-[-300%] top-[0] z-40 fixed bg-black transition-all duration-300">
        <div className="w-[100%] h-[100%] absolute g2"></div>
        <div className="w-[100%] h-[100%] absolute flex flex-wrap border-b-[.05px] border-[rgba(147,146,146,0.34)]">
          <div className="w-[100%] h-[10%] flex justify-between items-center px-5 border-b-[.05px] border-[rgba(147,146,146,0.34)]">
            <p className="text-[2rem]">W.D.R.O</p>
          <button onClick={closeNav} className="text-[2rem]"><i className="bi bi-x-circle"></i></button> 
          </div>
          <Nav1/>
        </div>
        </article>
        {children}

    
      </section>
    </section>
      </body>
    </html>
  );
}


function Profile(){
return(
<section className="w-[12.5%] h-[100%] border-l-[.05px] border-[rgba(147,146,146,0.34)] flex">
  <figure className="w-[100%] h-[100%] flex justify-center items-center">
    <figcaption className="w-[60%] h-[100%] flex-wrap content-center hidden lg:flex">
      <h1 className="w-[100%] text-[.7rem] xl:text-[.9rem] text-center font-bold uppercase">reza ojaghi</h1>
      <p className="w-[100%] text-[.5rem] xl:text-[.6rem] text-center text-zinc-300 uppercase">web developer</p>
    </figcaption>
   <Image
      src={profilePic}
      alt="Picture of the author"
      style={
        {
          width:'3rem',
          height:'3rem',
          objectFit:'cover',
          borderRadius:'50%'
        }
      }
    />
  </figure>
</section>
)
}

function Search(){

  const x=useRef()
  const x1=useRef()
  const x2=useRef()
  const x3=useRef()
  const x4=useRef()
  const x5=useRef()
  function searchNav(e){
    if(e.target.getAttribute('data-status')=='off'){
     x.current.style.display='flex' 
     x1.current.style.display='flex'
     x3.current.style.display='none'
     x4.current.style.display='none'
     x5.current.style.display='none'
     e.target.setAttribute('data-status','on')
     e.target.style.display='none'
    } 
  }
  function searchClose(e){
    x.current.style.display='none'
    x2.current.style.display='flex' 
    x3.current.style.display='flex' 
    x4.current.style.display='flex' 
    x5.current.style.display='flex' 
    x2.current.setAttribute('data-status','off')
  }

return(
<section className="w-[100vw] lg:w-[71%] h-[100%] border-l-[.05px] border-[rgba(147,146,146,0.34)] flex justify-around items-center z-40">
  <div ref={x} className=" w-[100%] md:w-[80%] h-[100%] justify-center items-center hidden">
  <button onClick={()=>searchClose(event)} ref={x1} className="hidden text-white w-[10%] h-[60%] text-[1rem] bg-[rgba(0,0,0,.3)] border-[.05px] border-[rgba(147,146,146,0.34)] justify-center items-center"><i className="bi bi-x-circle"></i></button>
  <input type="text" placeholder="type to search ..." className="text-white flex items-center w-[95%] h-[60%] text-[1rem] bg-[rgba(0,0,0,.3)] border-[.05px] border-[rgba(147,146,146,0.34)]"/>
  <button className="text-white w-[10%] lg:w-[5%] h-[60%] text-[1rem] bg-[rgba(0,0,0,.3)] border-[.05px] border-[rgba(147,146,146,0.34)] flex justify-center items-center">
  <i className="bi bi-search"></i>
  </button>
  </div>

<Image
      className='hidden lg:flex'
      src={I1}
      alt="Picture of the author"
      style={
        {
          width:'1.5rem',
          height:'1.5rem',
          objectFit:'cover',
          borderRadius:'50%'
        }
        
      }
    />
    <i data-status='off' ref={x2} onClick={()=>searchNav(event)} className="bi bi-search cursor-pointer text-[1rem] flex z-40"></i>
    <i ref={x3} className="bi bi-grid w-[1rem] h-[1rem] cursor-pointer"></i>
    <i ref={x4} className="bi bi-bell w-[1rem] h-[1rem] cursor-pointer"></i>
    <i ref={x5} className="bi bi-handbag w-[1rem] h-[1rem] cursor-pointer"></i>
</section>
)
}

function Logo(){
return(
<section className="w-[13.6%] h-[100%] hidden justify-center items-center lg:flex">
<p className="text-[2rem] font-extrabold" title="web developer reza ojaghi">W.D.R.O</p>
</section>
)
}

function NavH({navH}){
 
  return(
    <section className="w-[13.6%] h-[100%] flex lg:hidden justify-center items-center">
      <i onClick={navH} className="bi bi-list text-[2rem] cursor-pointer"></i>
    </section>
  )
}

function Nav(){
  return(
    <nav className="w-[100%] h-[100%]">
      <ul classNa className="w-[100%] h-[100%] flex gap-1 *:xl:text-[1rem] *:lg:text-[.65rem] *:capitalize items-center px-10">
      <li className="relative group">
          <Link className="flex gap-2 px-5 py-2 rounded-lg hover:bg-[rgba(255,255,255,0.2)] transition-all duration-300" href='/'>
          <i className="bi bi-house-door"></i> dashboard <i className="bi bi-chevron-down"></i>
          </Link>
          </li>
      <li className="relative group">
          <Link className="flex gap-2 px-5 py-2 rounded-lg hover:bg-[rgba(255,255,255,0.2)] transition-all duration-300" href='/analytics'>
          <i className="bi bi-house-door"></i> analytics<i className="bi bi-chevron-down"></i>
          </Link>
          </li>
      <li className="relative group">
          <Link className="flex gap-2 px-5 py-2 rounded-lg hover:bg-[rgba(255,255,255,0.2)] transition-all duration-300" href='/Calculator'>
          <i className="bi bi-house-door"></i> Calculator <i className="bi bi-chevron-down"></i>
          </Link>
          </li>
      <li className="relative group">
          <Link className="flex gap-2 px-5 py-2 rounded-lg hover:bg-[rgba(255,255,255,0.2)] transition-all duration-300" href='/email'>
          <i className="bi bi-house-door"></i> email <i className="bi bi-chevron-down"></i>
          </Link>
          </li>
      </ul>
    </nav>
  )
}
function Nav1(){
  const a=useRef()
  const[data,setData]=useState([])
  function aco(x){
      const v=a.current.children
      const v1=v[x-1].children
      data.push(x)
      data.map((val)=>{
        if(x!=val){
         const v1=v[val-1].children
        v1[0].setAttribute('data-status','off')
        v1[1].style.display='none'  
        } 
      })
     
      if(v1[0].getAttribute('data-status')=='off'){
        v1[1].style.display='flex'
        v1[0].setAttribute('data-status','on')
      }else{
        v1[1].style.display='none'
        v1[0].setAttribute('data-status','off')
      }
  }
 
  return(
    <nav className="w-[100%] h-[90%] overflow-y-scroll">
      <ul ref={a} className="w-[100%]  flex flex-wrap content-start gap-1 *:text-[2rem] z-50 *:capitalize items-center px-10">
      <li  className="group w-[100%] flex flex-wrap">
          <Link onClick={()=>aco(1)} data-status='off' className="flex w-[100%] gap-2 px-5 py-2 rounded-lg hover:bg-[rgba(255,255,255,0.2)] transition-all duration-300" href='/'>
          <i className="bi bi-house-door"></i> dashboard <i className="bi bi-chevron-down"></i>
          </Link> 
          </li>
      <li  className="group w-[100%] flex flex-wrap">
          <Link onClick={()=>aco(1)} data-status='off' className="flex w-[100%] gap-2 px-5 py-2 rounded-lg hover:bg-[rgba(255,255,255,0.2)] transition-all duration-300" href='/analytics'>
          <i className="bi bi-house-door"></i> analytics <i className="bi bi-chevron-down"></i>
          </Link> 
          </li>
      <li  className="group w-[100%] flex flex-wrap">
          <Link onClick={()=>aco(1)} data-status='off' className="flex w-[100%] gap-2 px-5 py-2 rounded-lg hover:bg-[rgba(255,255,255,0.2)] transition-all duration-300" href='/Calculator'>
          <i className="bi bi-house-door"></i> Calculator <i className="bi bi-chevron-down"></i>
          </Link> 
          </li>
      <li  className="group w-[100%] flex flex-wrap">
          <Link onClick={()=>aco(1)} data-status='off' className="flex w-[100%] gap-2 px-5 py-2 rounded-lg hover:bg-[rgba(255,255,255,0.2)] transition-all duration-300" href='/email'>
          <i className="bi bi-house-door"></i> email <i className="bi bi-chevron-down"></i>
          </Link> 
          </li>
      </ul>
    </nav>
  )
}

